Repository tetrachrome/chewbaaka, pull requests merged in 2020-12, with the labels that each got.

#209 Issue97
  src/components/biology/__tests__/__snapshots__/BiologyPage_Section_Lifecycle.test.js.snap
  src/components/biology/__tests__/__snapshots__/BiologyPage_Subsection_FeetAndClaws.test.js.snap
  src/components/biology/__tests__/__snapshots__/BiologyPage_Subsection_LearningToHunt.test.js.snap
  src/components/biology/config.js
  src/components/shared/ContentPageIntroSectionGeneric.js
  src/components/shared/ContentPageSectionHeadFragment.js
  src/components/shared/ContentPageSubsectionContentBinder.js
  src/components/shared/TextFormatter.js
Labels: bug fix, enhancement

#210 Port 'health_check.py' to Python3
  health_check.py
Labels: enhancement

#211 Update and refine top level README.md
  README.md
Labels: documentation

#212 Update top-level README.md
  README.md
Labels: documentation
